name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  openapi-client-generation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: make install-dev
    
    - name: Verify OpenAPI client generation
      run: |
        # Store hash of generated files
        find openapi -type f -exec sha256sum {} \; | sort > generated_files.hash
        # Generate again
        make generate-client
        # Compare hashes
        find openapi -type f -exec sha256sum {} \; | sort > new_generated_files.hash
        if ! diff generated_files.hash new_generated_files.hash; then
          echo "Generated files differ from committed files. Please run 'make generate-client' and commit the changes."
          exit 1
        fi

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: make install-dev
    
    - name: Run tests
      run: make test

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'
    
    - name: Install dependencies
      run: make install-dev
    
    - name: Build documentation
      run: make docs
    
    - name: Deploy documentation
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site
        publish_branch: gh-pages 